### ISSUE TITLE
validator Dockerfile and start.sh in private test network

### ISSUE THREAD

**Issue by d00m178** [karlfloersch/docker-pyeth-dev#19]
Hi.
What is the purpose of the last string in the Dockerfile for validator?
https://github.com/karlfloersch/docker-pyeth-dev/blob/master/validator/Dockerfile

`CMD ["pyethapp", "-m", "0", "--password", "/root/.config/pyethapp/password.txt", "-l", "eth.chain:info,eth.chainservice:info,eth.validator:info", "--log-file", "/root/log/log.txt", "-b", "$BOOTSTRAP_NODE", "run"]`

As far I know the client pyethapp runs from start.sh script:
https://github.com/karlfloersch/docker-pyeth-dev/blob/master/validator/start.sh
```
echo "Running command: $@"
$@
```

and because of these facts the validator node runs two process of pyethapp, one from CMD in Dockerfile and second - from start.sh

```
root@b9ee81047fbb:/ethereum# ps axu | grep pyeth
root         1  0.0  0.0   4492   648 pts/0    Ss+  15:31   0:00 sh /root/start.sh pyethapp -m 0 --unlock 1 --validate 1 --deposit 5000 --password /root/.config/pyethapp/password.txt -l eth.chain:info,eth.chainservice:info,eth.validator:info --log-file /root/log/log.txt -b enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@172.18.250.2:30303 run
root         8  6.9  0.9 357032 73672 pts/0    Sl+  15:31   0:28 /usr/local/bin/python /usr/local/bin/pyethapp -m 0 --unlock 1 --validate 1 --deposit 5000 --password /root/.config/pyethapp/password.txt -l eth.chain:info,eth.chainservice:info,eth.validator:info --log-file /root/log/log.txt -b enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@172.18.250.2:30303 run
root        33  0.0  0.0  12976   976 pts/1    S+   15:37   0:00 grep --color=auto pyeth
```

**Comment by t-nelis** [comment]
@d00m178 The CMD array is concatenated to the ENTRYPOINT array to form the command used to execute PID 1 (you can observe that in your ps output). `$@` within `start.sh` is thus equivalent to CMD in the Dockerfile -- it is expanded to a command a executed in a new process (PID 8) with the last line of `start.sh`.

The point is that you can [override CMD easily when creating a new container with the Docker CLI](https://docs.docker.com/engine/reference/builder/#cmd). If you do so, `start.sh` will still do its thing but finish by running your overriding command instead. Docker does not magically run it separately.

I don't think it's actually useful to create a new process in `start.sh` to run the CMD. If that helps, you could do [this](https://github.com/t-nelis/docker-pyeth-dev/commit/d94c9171e3c9c381b689472a32a107fbcb7fbaef) and your `ps` output would only show one process. (Feel free to issue a PR if you actually test it, but it's really not important.)

**Comment by d00m178** [comment]
@t-nelis thank you for your explanation.

**Comment by d00m178** [comment]
@t-nelis 
If I understand all correctly the script start.sh will run CMD part that concatenated to ENTRYPOINT only when we run that container from compose file for example.
In this case in container should be only one process with pyethapp and it should be equal CMD array:
`CMD ["pyethapp", "-m", "0", "--password", "/root/.config/pyethapp/password.txt", "-l", "eth.chain:info,eth.chainservice:info,eth.validator:info", "--log-file", "/root/log/log.txt", "-b", "$BOOTSTRAP_NODE", "run"]`

But when we want to run container from CLI  with command "make run-node ...." and "override" CMD part in Docker file, the command should be taken from Makefile:
```
pyethapp -m ${mine_percent} --unlock ${account} ${_validate} ${_deposit} ${_logout} --password /root/.config/pyethapp/password.txt -l ${log_config} --log-file /root/log/log.txt -b ${bootstrap_node} run
```
There are the difference between these commands. 
In second variant we have the keys  **--unlock**, **--validate**, **--deposit** etc, that are missing int the first variant.
So it's still not clear why we have two pids PID 1 and PID 8 when we start container via CLI.
And please note that processes in PID1 and PID2 both have the keys  **--unlock**, **--validate**, **--deposit**

UPD:
My question is because I need add to this test network more than one validator node.
So I decided to add validator services into docker-compose file to start my test network from one point.
I have changed validator/start.sh to start pyethapp and commented CMD string in Docker file.
So now I have only one process of pyethapp in my validator container, but I wonder if this correct in terms of PoS.

**Comment by t-nelis** [comment]
@d00m178 

>  If I understand all correctly the script start.sh will run CMD part that concatenated to ENTRYPOINT only when we run that container from compose file for example.

Technically, _only when it is not overridden_. docker-compose will set an arbitrary command if specified in the `command` property of a compose file. Because the `docker-compose.yml` file does not specify one here, then the default one set in the image metadata (via the Dockerfile CMD instruction) will be used, yes.

> In this case in container should be only one process with pyethapp and it should be equal CMD array:
> `CMD ["pyethapp", "-m", "0", "--password", "/root/.config/pyethapp/password.txt", "-l", "eth.chain:info,eth.chainservice:info,eth.validator:info", "--log-file", "/root/log/log.txt", "-b", "$BOOTSTRAP_NODE", "run"]`

To the extent to which Docker is involved, yes, the Docker engine will only create one process and being namespaced as it is, it will always have PID 1. Because you did not override the entrypoint (`--entrypoint` CLI option or `entrypoint` compose file property), then the command specified in the default entrypoint set in the image (via the Dockerfile ENTRYPOINT instruction) will be used for process 1. The "command" in Docker parlance (CMD in Dockerfile, command property in compose file) will be concatenated to it if it is set (whether it's set via the CLI, the Dockerfile, or the compose file). You can confirm this with `ps`.

This does not say anything about what process 1 does, it can start new processes on its own. At this point, the "command" part of the Docker container is just a set of arguments to the `start.sh` program.

> So it's still not clear why we have two pids PID 1 and PID 8 when we start container via CLI.

That's because `start.sh` forks a new process and has it execute a new command in it (the "command" part of the Docker container). They're not both executing pyethapp, only process 8 is. process 1 just waits for process 8 (pyethapp) to terminate and then will terminate itself.

I don't think there's any reason to keep a process waiting for another only to finish execution once it ends; that's why I suggested executing pyethapp in process 1.

> And please note that processes in PID1 and PID2 both have the keys --unlock, --validate, --deposit

Yes (they're called "arguments" in this context). Again, it should now be clear that process 1 is just holding them for when it's time to run pyethapp with those arguments; it doesn't do anything with them itself (just passes them along with `"$@"`).

Feel free to open a question on a technical forum more specific to Docker; I don't think we should hijack an issue tracker for these types of questions. I recommend some reading about POSIX, Docker and shell scripting.

> My question is because I need add to this test network more than one validator node.
So I decided to add validator services into docker-compose file to start my test network from one point.
I have changed validator/start.sh to start pyethapp and commented CMD string in Docker file.

It already did that (with the `"$@"` expansion), and you didn't have to comment CMD in the Dockerfile since you can override it in your compose file using the [`command` property](https://docs.docker.com/compose/compose-file/#command).

> So now I have only one process of pyethapp in my validator container, but I wonder if this correct in terms of PoS.

As explained above, there never was two pyethapp processes. One was executing start.sh which was waiting on the second which was executing pyethapp. You probably want one process total to execute both start.sh and then pyethapp in sequence; use `exec` for that and feel free to open a PR with my patch if you think it can reduce confusion for other people in the future. None of this should have any impact "in terms of PoS" I reckon.

**Comment by ChihChengLiang** [comment]
closed for inactivity, can reopen if further discussion required.
